import { Attribute } from '~/typings/game';

export const ANCESTRIES = [
  'human',
  'changeling',
  'clockwork',
  'dwarf',
  'goblin',
  'orc',
];

export const NOVICE_PATHS = ['magician', 'priest', 'rogue', 'warrior'];

export const EXPERT_PATHS = {
  faith: ['cleric', 'druid', 'oracle', 'paladin'],
  power: ['artificer', 'sorcerer', 'witch', 'wizard'],
  trickery: ['assassin', 'scout', 'thief', 'warlock'],
  war: ['berserker', 'fighter', 'ranger', 'spellbinder'],
};

export const MASTER_PATHS = {
  magic: [
    'abjurer',
    'aeromancer',
    'apocalyptist',
    'bard',
    'beastmaster',
    'chronomancer',
    'conjurer',
    'destroyer',
    'diviner',
    'enchanter',
    'geomancer',
    'healer',
    'hexer',
    'hydromancer',
    'illusionist',
    'mage_knight',
    'magus',
    'necromancer',
    'pyromancer',
    'runesmith',
    'savant',
    'shapeshifter',
    'stormbringer',
    'technomancer',
    'tenebrist',
    'thaumaturge',
    'theurge',
    'transmuter',
    'traveler',
    'woodwose',
  ],
  skill: [
    'acrobat',
    'avenger',
    'blade',
    'brute',
    'cavalier',
    'champion',
    'chaplain',
    'conqueror',
    'death_dealer',
    'defender',
    'dervish',
    'diplomat',
    'dreadnaught',
    'duelist',
    'engineer',
    'executioner',
    'exorcist',
    'explorer',
    'gladiator',
    'gunslinger',
    'infiltrator',
    'inquisitor',
    'jack_of_all_trades',
    'marauder',
    'miracle_worker',
    'myrmidon',
    'poisoner',
    'sentinal',
    'sharpshooter',
    'templar',
    'weapon_master',
    'zealot',
  ],
};

export const ATTRIBUTES: Attribute[] = [
  'strength',
  'agility',
  'intellect',
  'will',
];
