import { CwnCharacterData } from '~/typings/cwn/characterData';

export const CWN_SKILL_UNTRAINED = -1;
const CWN_DEFAULT_ATTRIBUTE_SCORE = 10;

export const DEFAULT_VALUES: CwnCharacterData = {
  type: 'cwn',
  name: '',
  level: 1,
  description: '',
  attribute_strength: CWN_DEFAULT_ATTRIBUTE_SCORE,
  attribute_dexterity: CWN_DEFAULT_ATTRIBUTE_SCORE,
  attribute_constitution: CWN_DEFAULT_ATTRIBUTE_SCORE,
  attribute_intelligence: CWN_DEFAULT_ATTRIBUTE_SCORE,
  attribute_wisdom: CWN_DEFAULT_ATTRIBUTE_SCORE,
  attribute_charisma: CWN_DEFAULT_ATTRIBUTE_SCORE,
  background_name: '',
  background_details: '',
  contacts: [],
  skill_administer: CWN_SKILL_UNTRAINED,
  skill_connect: CWN_SKILL_UNTRAINED,
  skill_drive: CWN_SKILL_UNTRAINED,
  skill_exert: CWN_SKILL_UNTRAINED,
  skill_fix: CWN_SKILL_UNTRAINED,
  skill_heal: CWN_SKILL_UNTRAINED,
  skill_know: CWN_SKILL_UNTRAINED,
  skill_lead: CWN_SKILL_UNTRAINED,
  skill_notice: CWN_SKILL_UNTRAINED,
  skill_perform: CWN_SKILL_UNTRAINED,
  skill_program: CWN_SKILL_UNTRAINED,
  skill_punch: CWN_SKILL_UNTRAINED,
  skill_shoot: CWN_SKILL_UNTRAINED,
  skill_sneak: CWN_SKILL_UNTRAINED,
  skill_survive: CWN_SKILL_UNTRAINED,
  skill_stab: CWN_SKILL_UNTRAINED,
  skill_talk: CWN_SKILL_UNTRAINED,
  skill_trade: CWN_SKILL_UNTRAINED,
  skill_work: CWN_SKILL_UNTRAINED,
  remaining_skill_points: 0,
  foci: [],
  edges: [],
  health_max: 1,
  health_current: 1,
  system_strain_current: 0,
  system_strain_max: CWN_DEFAULT_ATTRIBUTE_SCORE,
  traumatic_hit: false,
  major_injuries: [],
  // attack_bonus_base: 0,
  // attack_bonus_melee: 0,
  // attack_bonus_ranged: 0,
  // initiative_bonus: 0,
  // equipment: [],
  // weapons: [],
  // armors: [],
  // currency_copper: 0,
  // currency_silver: 0,
  // currency_gold: 0,
};
